#+STARTUP: indent

#+TITLE: Webmacs

* Description

Webmacs is a package which lets other people watch you editing stuff in Emacs on every modern web browser.

* Usage
** Server Side

The server is written in Clojure. Currently no pre-built jar is available, so you need [[http://leiningen.org][leiningen]].

#+BEGIN_SRC sh
$ git clone https://github.com/the-kenny/webmacs.git
$ cd webmacs
$ lein run
#+END_SRC

This will run a local webserver on port 3000. The entry point for Emacs is port 9881.

You can change these defaults via environment variables ~EMACS_PORT~ and ~WEB_PORT~.

** Emacs Side

1) Put webmacs.el somewhere in your load path
2) Load webmacs.el

#+BEGIN_SRC lisp
(require 'webmacs)
#+END_SRC

3) Connect to Server

#+BEGIN_SRC lisp
M-x webmacs-open-connection RET RET RET
#+END_SRC

4) Enable ~webmacs-mode~ in every buffer which you want to publish

#+BEGIN_SRC lisp
M-x webmacs-mode
#+END_SRC

** Browser

Published buffers are referenced via their name:

#+BEGIN_EXAMPLE
http://localhost:3000/emacs/<buffer-name>
#+END_EXAMPLE

* Future Goals

Webmacs is in pretty rough shape. A major feature missing is font-lock (syntax highlighting), and many other convenient things like listing available buffers isn't implemented yet.

See TODO.org for things that needs to be done.

* License

Copyright © 2012 Moritz Ulrich

Distributed under the Eclipse Public License, the same as Clojure.
